### ISSUE TITLE
Database Connection

### ISSUE THREAD

**Issue by abidharyanda** [vaadin-marcus/spring-boot-todo#3]
Hi All,

I want to know, what is database use in this project ? and how to connected with database ?

Thank you

**Comment by ECSDELS** [comment]
Hi,

I get H2 exception when doing ADD in GUI using SPRING version 2.0.1.RELEASE, any hints?
It is OK using1.4.0.RELEASE.

Caused by: org.h2.jdbc.JdbcSQLException: Unique index or primary key violation: "PRIMARY KEY ON PUBLIC.TODO(ID)"; SQL statement:
insert into todo (done, text, id) values (?, ?, ?) [23505-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357) ~[h2-1.4.197.jar:1.4.197]

**Comment by CharlesNice** [comment]
I have the same Problem as above, IDK whats goin on

**Comment by CharlesNice** [comment]
nvm just use GenerationType.IDENTITY instead of GenerationType.AUTO

**Comment by marcushellberg** [comment]
Thanks for taking a look. I updated the code accordingly so it should work with spring boot 2 now.
